# Generated by Django 4.2.8 on 2024-01-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_name', models.CharField(max_length=50)),
                ('sales_employee_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('so_number', models.CharField(max_length=20)),
                ('artikel', models.CharField(max_length=20)),
                ('warna', models.CharField(max_length=20)),
                ('nomor_mesin', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesorder.sales')),
            ],
        ),
    ]
